TRUNCATE TABLE public.keyword_info RESTART IDENTITY;

ALTER TABLE public.keyword_info
  ADD COLUMN IF NOT EXISTS sn BIGINT GENERATED BY DEFAULT AS IDENTITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'keyword_info_pkey'
      AND conrelid = 'public.keyword_info'::regclass
  ) THEN
    ALTER TABLE public.keyword_info
      ADD CONSTRAINT keyword_info_pkey PRIMARY KEY (sn);
  END IF;
END $$;
